In [14]:
import pandas as pd

In [15]:
def describe_df(df):
    descriptive_summary = df.describe(include="all").T
    descriptive_summary["n_unique"] = df.nunique()
    descriptive_summary["null_count"] = df.isnull().sum()
    descriptive_summary["skewness"] = df.skew(numeric_only=True)
    descriptive_summary["kurtosis"] = df.kurtosis(numeric_only=True)
    descriptive_summary["type"] = df.dtypes
    
    try:
        descriptive_summary = descriptive_summary.drop(columns=["unique", "top", "freq"])
    except:
        pass

    return descriptive_summary

In [16]:
ventas_cdmx_df = pd.read_excel('../data/_raw/ventas_CDMX_aspel_export.xlsx', skiprows=3)
ventas_cdmx_df

,FOLIO,FECHA,SUCURSAL,CLAVE_PROD,DESCRIPCION,CATEGORIA,CANTIDAD,PRECIO_UNIT,SUBTOTAL,IVA,TOTAL,FORMA_PAGO,RFC_CLIENTE,VENDEDOR,ESTATUS,__UNNAMED__,Unnamed: 15
0,10000,2023-01-08,CDMX-Norte,ARROZ_1KG_LA,Arroz 1kg La Merced,Abarrotes,2,24.93,49.86,7.98,N/D,Efectivo,CGPO985807XYZ,Marta L.,PAGADO,NaN,NaN
1,10001,2023-01-11,CDMX-Sur,ACEITE_1L_NU,Aceite 1L Nutrioli,Abarrotes,49,44.06,2158.7,345.39,2504.09,Efectivo,IGBL765545XYZ,Carlos R.,PAGADO,NaN,NaN
2,10002,2023-01-02,CDMX-Norte,SUAVITEL_800,Suavitel 800ml,Limpieza,24,58.72,1409.23,225.48,1634.71,Tarjeta,LVEJ840074123,Carlos R.,PAGADO,NaN,NaN
3,10003,2023-01-09,CDMX-Sur,SERVILLETAS_,Servilletas Kleenex x100,Higiene,16,28.38,454.15,72.66,526.81,Crédito 30 días,FAIG810716123,José G.,PAGADO,NaN,NaN
4,10004,2023-01-08,CDMX-Norte,PAPEL_HIGIÉN,Papel Higiénico Petalo x4,Higiene,30,45.26,1357.72,217.24,1574.96,Tarjeta,ZDMT757588ABC,Marta L.,PENDIENTE,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2236,12171,2024-12-23,CDMX-Sur,FRIJOL_BAYO_,Frijol bayo 1kg,Abarrotes,35,34.52,1208.36,193.34,1401.7,Transferencia,UJJB758586ABC,Ana P.,PAGADO,NaN,NaN
2237,12172,2024-12-02,CDMX-Sur,ACEITE_1L_NU,Aceite 1L Nutrioli,Abarrotes,15,41.55,623.29,99.73,723.02,Transferencia,RLLF849572XYZ,Ana P.,PAGADO,NaN,NaN
2238,12173,2024-12-09,CDMX-Sur,CLORO_CLORAL,Cloro Cloralex 1L,Limpieza,44,20.41,898.1,143.7,1041.8,Transferencia,ARMN946039XYZ,Marta L.,PAGADO,NaN,NaN
2239,12174,2024-12-18,CDMX-Sur,DETERGENTE_A,Detergente Ariel 1kg,Limpieza,40,80.73,3229.23,516.68,3745.91,Tarjeta,GWYO930931ABC,José G.,PAGADO,NaN,NaN
2240,12175,2024-12-28,CDMX-Norte,SUAVITEL_800,Suavitel 800ml,Limpieza,23,53.51,1230.69,196.91,1427.6,Tarjeta,VJTN734774XYZ,Carlos R.,PAGADO,NaN,NaN

In [ ]:
ventas_cdmx_df['ERROR_FECHA'] = ventas_cdmx_df['FECHA'].apply(
    lambda x: x if pd.to_datetime(x, errors='coerce') is pd.NaT else None
)

errores_fecha_unicos = ventas_cdmx_df['ERROR_FECHA'].dropna().unique()

print("Valores únicos que no pudieron convertirse:")
print(errores_fecha_unicos)

ventas_cdmx_df['FECHA'] = pd.to_datetime(ventas_cdmx_df['FECHA'], errors='coerce')

Valores únicos que no pudieron convertirse:
['Sin fecha']

In [18]:
descriptive_summary = describe_df(ventas_cdmx_df)
descriptive_summary

,count,mean,std,min,25%,50%,75%,max,n_unique,null_count,skewness,kurtosis,type
FOLIO,2241.0,11088.493083,627.843393,10000.0,10545.0,11087.0,11630.0,12175.0,2176,0,0.000041,-1.201506,int64
FECHA,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,685,0,NaN,NaN,object
SUCURSAL,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,NaN,NaN,object
CLAVE_PROD,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,0,NaN,NaN,object
DESCRIPCION,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,0,NaN,NaN,object
CATEGORIA,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,NaN,NaN,object
CANTIDAD,2241.0,25.602856,14.687436,1.0,12.0,26.0,38.0,50.0,50,0,-0.018307,-1.257857,int64
PRECIO_UNIT,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1600,0,NaN,NaN,object
SUBTOTAL,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2057,0,NaN,NaN,object
IVA,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010,0,NaN,NaN,object
TOTAL,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2073,0,NaN,NaN,object
FORMA_PAGO,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,0,NaN,NaN,object
RFC_CLIENTE,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2176,0,NaN,NaN,object
VENDEDOR,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0,NaN,NaN,object
ESTATUS,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,NaN,NaN,object
__UNNAMED__,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2241,NaN,NaN,float64
Unnamed: 15,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2241,NaN,NaN,float64
ERROR_FECHA,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2182,NaN,NaN,object